Resolve "multiselect improvements"
wxsms/uiv pull request #343
Opened 2020-08-17 09:01 UTC by kadirkahraman

### Is this a bug fix or enhancement?

It is enhancements

### Is there a related issue?

Related with #324 
MR reviews is completed (#325 )

### Any Breaking changes?

2020-08-18 05:50 UTC, kadirkahraman commented
hi @wxsms . 
I've developed some features in #324 . I've used scoped slots for custom options. I've also added samples for MultiSelect.md but I couldn't find the file in latest version. I think you moved. I'm adding edited .md file in comment. You can also inspect it



[MultiSelect.md.zip](https://github.com/uiv-lib/uiv/files/5088441/MultiSelect.md.zip)

2020-08-25 01:59 UTC, wxsms requested changes
Hello, pls read my comments and see if you agree with my suggestions, thanks.

2020-08-25 01:59 UTC, wxsms commented on src/components/select/MultiSelect.vue
> +          @keyup="searchClicked"
could simplified as `@keyup.enter=`

2020-08-25 01:59 UTC, wxsms commented on src/components/select/MultiSelect.js
> +      if (event.key === 'Enter') {
this could be remove after using `@keyup.enter=` which makes could simpler

2020-08-25 01:59 UTC, wxsms commented on src/components/select/MultiSelect.vue
> +            <a role="button" v-if="customOptionsVisible" style="outline: 0">
you may need to change the next `v-if` to `v-else-if` ?

2020-08-25 01:59 UTC, wxsms commented on src/components/select/MultiSelect.js
> +    fireEvent: {
I think the props is not neccessary. pls simply fire the `search` event whiout config.

2020-08-29 08:40 UTC, wxsms approved these changes

2020-08-29 08:41 UTC, merged